semantic error: Found type mismatch in 'add'(character and integer).
 --> tests/errors/test_set1.py:6:5
  |
6 |     a.add('err')
  |     ^^^^^^^^^^^^ 
